//go:build ignore

// gen.go writes table.go from the standard library's encoding/xml.HTMLEntity,
// so that a document decoded through this package and one decoded through
// encoding/xml with Decoder.Entity = xml.HTMLEntity read the same.
//
//	go run gen.go
package main

import (
	"bytes"
	"encoding/xml"
	"fmt"
	"go/format"
	"os"
	"runtime"
	"sort"
)

func main() {
	names := make([]string, 0, len(xml.HTMLEntity))
	for n := range xml.HTMLEntity {
		names = append(names, n)
	}
	sort.Strings(names)
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by gen.go from encoding/xml.HTMLEntity of %s; DO NOT EDIT.\n\n", runtime.Version())
	b.WriteString("package htmlentity\n\n")
	b.WriteString("// table holds the named character references of HTML 4, sorted by name\n")
	b.WriteString("// for the binary search in Lookup.\n")
	b.WriteString("var table = [...]entry{\n")
	for _, n := range names {
		fmt.Fprintf(&b, "\t{%q, %q},\n", n, xml.HTMLEntity[n])
	}
	b.WriteString("}\n")
	src, err := format.Source(b.Bytes())
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile("table.go", src, 0o644); err != nil {
		panic(err)
	}
}
